export const LIFE_EVENTS = [
  {
    slug: "divorce",
    label: "Divorce",
    emoji: "💔",
    category: "Relationships",
    description: "Navigating the complexities of divorce and co-parenting",
  },
  {
    slug: "grief",
    label: "Grief",
    emoji: "🕯️",
    category: "Loss",
    description: "Processing loss of a loved one",
  },
  {
    slug: "job-loss",
    label: "Job Loss",
    emoji: "💼",
    category: "Career",
    description: "Recovering from job loss or career transition",
  },
  {
    slug: "health-crisis",
    label: "Health Crisis",
    emoji: "🏥",
    category: "Health",
    description: "Coping with serious illness or health diagnosis",
  },
  {
    slug: "addiction-recovery",
    label: "Addiction Recovery",
    emoji: "🌱",
    category: "Wellness",
    description: "Supporting recovery from substance abuse or addiction",
  },
  {
    slug: "bankruptcy",
    label: "Bankruptcy",
    emoji: "📉",
    category: "Finance",
    description: "Rebuilding after financial hardship",
  },
  {
    slug: "empty-nest",
    label: "Empty Nest",
    emoji: "🏠",
    category: "Life Stage",
    description: "Adjusting to children moving out or growing up",
  },
  {
    slug: "career-change",
    label: "Career Change",
    emoji: "🚀",
    category: "Career",
    description: "Transitioning to a new career path",
  },
  {
    slug: "relationship-breakup",
    label: "Relationship Breakup",
    emoji: "💔",
    category: "Relationships",
    description: "Healing from a significant relationship ending",
  },
  {
    slug: "parenting-challenges",
    label: "Parenting Challenges",
    emoji: "👨‍👩‍👧‍👦",
    category: "Family",
    description: "Support for challenging parenting situations",
  },
  {
    slug: "retirement",
    label: "Retirement",
    emoji: "🎯",
    category: "Life Stage",
    description: "Adjusting to retirement and finding new purpose",
  },
  {
    slug: "relocation",
    label: "Relocation",
    emoji: "🏘️",
    category: "Life Change",
    description: "Adapting to moving to a new place",
  },
];
